name: flutter_inheritedwidget_demo_v2
description: Flutter app demonstrating multiple raw InheritedWidgets (value + color).
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
